name: AgentLogger CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_agentlogger
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h localhost -p 5432; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
    
    - name: Lint with flake8
      run: |
        pip install flake8
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Type check with mypy (allow failures)
      run: |
        pip install mypy types-requests
        mypy app --ignore-missing-imports || true
      continue-on-error: true
    
    - name: Create test database
      env:
        PGPASSWORD: postgres
      run: |
        psql -h localhost -U postgres -c "CREATE DATABASE test_agentlogger;" || true
    
    - name: Run database migrations
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_agentlogger
        SECRET_KEY: test_secret_key_for_ci_cd_testing
        GROQ_API_KEY: test_groq_key_for_ci_cd
        ENVIRONMENT: testing
      run: |
        alembic upgrade head
    
    - name: Test with pytest
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_agentlogger
        SECRET_KEY: test_secret_key_for_ci_cd_testing
        GROQ_API_KEY: test_groq_key_for_ci_cd
        ENVIRONMENT: testing
      run: |
        pytest tests/ -v --tb=short
    
    - name: Check frontend dependencies
      run: |
        ls -la frontend/
        test -f frontend/package-lock.json && echo "package-lock.json found" || echo "package-lock.json not found"
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    
    - name: Test frontend build
      run: |
        cd frontend
        npm ci
        npm run build
        # Skip type-check for now due to potential issues
        # npm run type-check

  test-docker:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Test Docker build
      run: |
        docker build -t agentlogger-test -f deployment/Dockerfile .
        docker run --rm agentlogger-test python -c "import app; print('Backend import successful')"

  build:
    runs-on: ubuntu-latest
    needs: [test, test-docker]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push backend
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./deployment/Dockerfile.prod
        push: true
        tags: agentlogger/api:latest,agentlogger/api:${{ github.sha }}
        cache-from: type=registry,ref=agentlogger/api:buildcache
        cache-to: type=registry,ref=agentlogger/api:buildcache,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /opt/agentlogger
          docker-compose -f deployment/docker-compose.prod.yml pull
          docker-compose -f deployment/docker-compose.prod.yml up -d
          docker system prune -af 