name: Build and Publish CLI Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine wheel setuptools
    
    - name: Lint CLI package
      run: |
        pip install flake8
        flake8 cli/ --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Test CLI package build
      run: |
        cd cli
        python -m build --wheel --sdist
        twine check dist/*
    
    - name: Publish to PyPI
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages-dir: cli/dist/
        verify-metadata: true
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cli-packages
        path: cli/dist/
        retention-days: 30 